### ISSUE TITLE
On the Cairo file in L1 folder 

### ISSUE THREAD

**Issue by DecentrilizedMan** [aave-starknet-project/aave-starknet-bridge#122]
In this file , why you set BRIDGE_REWARD_MESSAGE = 1 and the other message as 2 ?

How do your team think about such message passing ?

**Comment by achab** [comment]
Hi @DecentrilizedMan, these values should just be the same on L1 and L2 sides. It helps L1 bridge checking that it consumes the correct message sent by L2. These values could be different, for instance `BRIDGE_REWARD_MESSAGE = 97` and `WITHDRAW_MESSAGE = 36`.

Does it answer the question?

**Comment by DecentrilizedMan** [comment]
Did you mean these values can be served  as flags ?
Like when we saw these values in the payload(0) , i can know what the
message it is carrying ?

Karl Yu ***@***.***> 于2022年10月19日周三 09:38写道：

**Comment by achab** [comment]
It's just a flag to distinguish messages sent by L2 bridge to L1 bridge. These values should just be unique at the level of our app.
