### ISSUE TITLE
Add requirements.txt for python dependencies

### ISSUE THREAD

**Issue by achab** [aave-starknet-project/aave-starknet-bridge#17]

**Comment by achab** [comment]
@swapnilraj A nice alternative to requirements.txt file is to use [poetry](https://python-poetry.org/). It lets you lock the versions of the dependencies, like with package-lock.json or yarn.lock files.

**Comment by swapnilraj** [comment]
Yea that sounds good to me

**Comment by swapnilraj** [comment]
We have poetry configured
