### ISSUE TITLE
update swapnil's package to use latest version of L1 StaticATokenLM contract

### ISSUE THREAD

**Issue by achab** [aave-starknet-project/aave-starknet-bridge#39]

**Comment by JorikSchellekens** [comment]
What is this blocked on?

**Comment by achab** [comment]
It was blocked by the PR not merged yet on Adrey's repo. I'll update it now and adapt the changes

**Comment by achab** [comment]
It was blocked by the PR not merged yet on Adrey's repo. I'll update it now and adapt the changes
